export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_REQUEST_SUCCESS = 'USER_REGSITER_REQUEST_SUCCESS';
export const USER_REGISTER_REQUEST_FAIL = 'USER_REGISTER_REQUEST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_REQUEST_SUCCESS = 'USER_DETAILS_REQUEST_SUCCESS';
export const USER_DETAILS_REQUEST_FAIL = 'USER_DETAILS_REQUEST_FAIL';
export const USER_DETAILS_REQUEST_RESET = 'USER_DETAILS_REQUEST_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_REQUEST_SUCCESS = 'USER_UPDATE_PROFILE_REQUEST_SUCCESS';
export const USER_UPDATE_PROFILE_REQUEST_FAIL = 'USER_UPDATE_PROFILE_REQUEST_FAIL';
export const USER_UPDATE_PROFILE_REQUEST_RESET = 'USER_UPDATE_PROFILE_REQUEST_RESET';