export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';